# All models must be added here.
# If you cannot modify this file, copy it to a directory with write permissions,
# and set the DEEPNOG_CONFIG environment variable to this dir, e.g.
# $ export DEEPNOG_CONFIG="/home/$USER/deepnog_config"

database:
  eggNOG5:
    # taxonomic levels
    - 1
    - 2
    - 29
    - 237
    - 468
    - 506
    - 561
    - 772
    - 815
    - 976
    - 1117
    - 1150
    - 1224
    - 1236
    - 1239
    - 1268
    - 1297
    - 1386
    - 1653
    - 1762
    - 2157
    - 2759
    - 3699
    - 4447
    - 4751
    - 4776
    - 4890
    - 4891
    - 5204
    - 5338
    - 5653
    - 5794
    - 5878
    - 6231
    - 6236
    - 6656
    - 7147
    - 7214
    - 7711
    - 7742
    - 7898
    - 8459
    - 9263
    - 9443
    - 9989
    - 28211
    - 28216
    - 28221
    - 28890
    - 29547
    - 31979
    - 32066
    - 33090
    - 33154
    - 33208
    - 33213
    - 33342
    - 33554
    - 33958
    - 35493
    - 38820
    - 40674
    - 41294
    - 50557
    - 68525
    - 69277
    - 71274
    - 72273
    - 72275
    - 80864
    - 82115
    - 85004
    - 85010
    - 85013
    - 85023
    - 85025
    - 85026
    - 91061
    - 91561
    - 91835
    - 112252
    - 117743
    - 117747
    - 119060
    - 119089
    - 135613
    - 135614
    - 135619
    - 135623
    - 147545
    - 147550
    - 155619
    - 183963
    - 186801
    - 186822
    - 186928
    - 200643
    - 201174
    - 203691
    - 204441
    - 204457
    - 213115
    - 267890
    - 314146
    - 355688
    - 541000
    - 544448
    - 768503
    - 909932
    #- 10841  # Example 1: Uncomment this line, if you created a Microviridae model
  cog2020:
    - 1
  #OMA:      # Example 2: Uncomment this line and the following, if you
    #- xy    #            created a model for the 'xy' level of OMA.
             # NOTE: Currently, a level must be provided, even if the database
             #       does not use levels. Simply use a placeholder 1 or similar.
             # NOTE 2: Indentation matters

architecture:
  # The default DeepNOG network
  deepnog:
    module: deepnog
    class: DeepNOG
    encoding_dim: 10
    kernel_size:
      - 8
      - 12
      - 16
      - 20
      - 24
      - 28
      - 32
      - 36
    n_filters: 150
    dropout: 0.3
    pooling_layer_type: 'max'

  deepfam:
    module: deepfam
    class: DeepFam
    kernel_size:
      - 8
      - 12
      - 16
      - 20
      - 24
      - 28
      - 32
      - 36
    n_filters: 250
    dropout: 0.3
    hidden_units: 2000

  deepfam_light:
    module: deepfam
    class: DeepFam
    kernel_size:
      - 8
      - 12
      - 16
      - 20
      - 24
      - 28
      - 32
      - 36
    n_filters: 150
    dropout: 0.3
    hidden_units: 1500

config:
  - custom
